version: "2"
linters:
  enable:
    - copyloopvar
    - gocyclo
    - inamedparam
    - misspell
    - revive
    - testifylint
    - whitespace
    - govet
    - unused
    - errcheck
    - ineffassign
    - staticcheck
  settings:
    gocyclo:
      min-complexity: 15
    govet:
      enable-all: true
    misspell:
      locale: US
    testifylint:
      disable:
        - require-error
        - error-nil
        - formatter
        - encoded-compare
    staticcheck:
      checks: ["all", "-QF1001"]
    revive:
      rules:
        - name: use-any
          disabled: false
  exclusions:
    generated: strict
    rules:
      - linters:
          - gocyclo
        path: _test\.go
      - path: (.+)\.go$
        text: should have a package comment
      - path: (.+)\.go$
        text: exported (.+) should have comment( \(or a comment on this block\))? or be unexported
    paths:
      - .github
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
  settings:
    gofmt:
      simplify: true
  exclusions:
    generated: strict
    paths:
      - .github
