name: Test
on:
  push:
    branches:
      - "**"
    tags-ignore:
      - "v*.*.*"
  pull_request:
    branches:
      - "**"
jobs:
  tests:
    name: Unit and integrations tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ["1.19", "1.20"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
      - name: Run tests
        run: |
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV
          echo "$(go env GOPATH)/bin" >> $GITHUB_PATH
          go test -v -race ./...

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51
          args: --timeout 5m
